- name: install mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: start and enable mysql
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: setting root password 
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{MYSQL_ROOT_PASSWORD}}