- name: install mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: start and enable mysql
  ansible.builtin.service:
    name: mysqld
    state: restarted
    enabled: yes

- name: install mysql python libraries
  ansible.builtin.pip:
    executable: pip3.9
    name: "{{item}}"
  loop:
    - botocore
    - boto3

- name: setting root password 
  ansible.builtin.command: mysql_secure_installation --set-root-pass {{MYSQL_ROOT_PASSWORD}}